# Generated by Django 3.0 on 2022-01-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
    ]
